/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.5.4")
    implementation("org.springframework.boot:spring-boot-starter-web:2.5.4")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.5.4")
    implementation("org.liquibase:liquibase-core:4.4.3")
    implementation("org.liquibase:liquibase-maven-plugin:4.4.3")
    implementation("javax.xml.bind:jaxb-api:2.4.0-b180830.0359")
    implementation("org.projectlombok:lombok:1.18.20")
    implementation("org.mapstruct:mapstruct:1.4.2.Final")
    implementation("am.ik.yavi:yavi:0.8.3")
    runtimeOnly("com.h2database:h2:1.4.200")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.5.4")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.4")
}

group = "mrvladimort.pet"
version = "0.0.1-SNAPSHOT"
description = "sbm-beer-service"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
